# Generated by Django 5.2.1 on 2025-05-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=100, verbose_name='CPF')),
                ('funcao', models.CharField(max_length=100, verbose_name='CPF')),
                ('contratacao', models.DateField(verbose_name='Data de Contratação')),
            ],
        ),
    ]
