# Generated by Django 5.2.1 on 2025-05-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genitores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Identificação')),
                ('sexo', models.CharField(max_length=100, verbose_name='Sexo')),
                ('data', models.DateField(verbose_name='Nascimento')),
                ('gen_masc', models.CharField(max_length=100, verbose_name='Genitor Masculino')),
                ('gen_fem', models.CharField(max_length=100, verbose_name='Genitor Feminino')),
                ('preco_animal', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor estimado do animal')),
                ('preco_semen', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor do Sêmen')),
            ],
        ),
        migrations.CreateModel(
            name='Pasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pasto', models.CharField(max_length=100, verbose_name='Nome')),
                ('piquetes', models.IntegerField(verbose_name='Piquetes')),
                ('reforma', models.DateField(verbose_name='Data de Reforma')),
                ('tratamento', models.TextField(verbose_name='Adubos aplicados')),
                ('custo', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Custo estimado da última reforma')),
            ],
        ),
        migrations.CreateModel(
            name='Populacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('quantidade', models.IntegerField(verbose_name='Número de animais')),
                ('preco_animal', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor estimado do animal')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço da população')),
                ('sexo', models.TextField(verbose_name='Sexo')),
                ('idade', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Idade estimada')),
                ('Genealogia', models.TextField(verbose_name='Genealogia')),
            ],
        ),
        migrations.AddField(
            model_name='contato',
            name='telefone',
            field=models.CharField(default=1, max_length=100, verbose_name='Telefone'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contato',
            name='funcao',
            field=models.CharField(max_length=100, verbose_name='Função'),
        ),
    ]
