# Generated by Django 5.2.1 on 2025-05-24 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_genitores_pasto_populacao_contato_telefone_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contato',
            new_name='Colaboradores',
        ),
    ]
