# Generated by Django 5.2.1 on 2025-05-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_contato_colaboradores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genitores',
            name='gen_fem',
            field=models.CharField(max_length=100, verbose_name='Genitor Feminino (NA = desconhecido)'),
        ),
        migrations.AlterField(
            model_name='genitores',
            name='gen_masc',
            field=models.CharField(max_length=100, verbose_name='Genitor Masculino (NA = desconhecido)'),
        ),
        migrations.AlterField(
            model_name='populacao',
            name='Genealogia',
            field=models.TextField(verbose_name='Genealogia (NA = desconhecido)'),
        ),
    ]
