# Generated by Django 5.2.1 on 2025-05-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_genitores_gen_fem_alter_genitores_gen_masc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasto',
            name='tamanho',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='Tamanho (hectares)'),
            preserve_default=False,
        ),
    ]
